# Generated by Django 4.0.2 on 2022-02-12 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome')),
                ('cpf_cnpj', models.IntegerField(verbose_name='CPF/CNPJ')),
                ('rg_ie', models.IntegerField(verbose_name='RG/IE')),
                ('telefone1', models.IntegerField(blank=True, verbose_name='Telefone1')),
                ('telefone2', models.IntegerField(blank=True, verbose_name='Telefone2')),
                ('email', models.EmailField(blank=True, max_length=50, verbose_name='E-mail')),
                ('endereco', models.CharField(max_length=120, verbose_name='Endereço')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
                ('servico', models.CharField(max_length=100, verbose_name='Serviço')),
                ('descricao', models.TextField(max_length=40, verbose_name='Descrção')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Os',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated', models.DateField(auto_now=True, verbose_name='Atualizado em:')),
                ('relato', models.TextField(max_length=200, verbose_name='Relato')),
                ('defeito_encontrado', models.TextField(max_length=200, verbose_name='Defeito')),
                ('desc_serv', models.TextField(max_length=200, verbose_name='Descrição do Serviço')),
                ('garantia', models.DateField(verbose_name='Garantia')),
                ('serv_valor', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor do Serviço')),
                ('pec_valor', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor das Peças')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.servico', verbose_name='Serviço')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
