# Generated by Django 4.0.2 on 2022-02-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg_ie',
            field=models.CharField(max_length=12, verbose_name='RG/IE'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone1',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone1'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone2',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone2'),
        ),
    ]
